# See config.example.yml for documentation.

object: orig/R8IE78/sys/main.dol
hash: d7eb579ca3fdd05474e268582aa34ce667533066
symbols: config/R8IE78/symbols.txt
splits: config/R8IE78/splits.txt
ldscript_template: config/R8IE78/ldscript.lcf
# mw_comment_version: 14
# See config.example.yml for a list.
